default_stages: [commit]

default_language_version:
  python: python3.10

repos:

  # Note that all of the `local` repo hooks are version managed by
  # poetry. This is done to ensure that the same versions are used locally
  # as in CI. Update them via poetry when needed.
  - repo: local
    hooks:
      # Ensure poetry installed package versions are up-to-date with lockfile
      - id: poetry-install
        entry: poetry lock --check
        language: system
        name: poetry    - Python package installation
        pass_filenames: false
        types_or: [python, html]

      # Django template formatting - will amend files
      - id: djhtml
        entry: poetry run djhtml
        language: system
        name: djhtml    - Django template formatting
        types: [html]
        files: ./templates/.*\.html$

      # python linting and more
      - id: ruff
        entry: poetry run ruff
        language: system
        name: ruff      - Python import sorting
        types: [python]
        args: [--fix, --exit-non-zero-on-fix]

      # python code formatting - will amend files
      - id: black
        entry: poetry run black
        language: system
        name: black     - Python code formatting
        types: [python]

      # python static type checking
      - id: mypy
        entry: poetry run mypy
        language: system
        name: mypy      - Python type checking
        types: [python]
