# Generated by Django 5.1.7 on 2025-04-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amiqus", "0003_alter_client_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="check_type",
            field=models.CharField(
                choices=[
                    ("document", "Document"),
                    (
                        "document_with_address_information",
                        "Document with Address Information",
                    ),
                    (
                        "document_with_driving_licence_information",
                        "Document with Driving Licence Information",
                    ),
                    ("facial_similarity_photo", "Facial Similarity (photo)"),
                    ("facial_similarity_photo_fully_auto", "Facial Similarity (auto)"),
                    ("facial_similarity_video", "Facial Similarity (video)"),
                    ("known_faces", "Known Faces"),
                    ("identity_enhanced", "Identity (enhanced)"),
                    ("watchlist_enhanced", "Watchlist (enhanced)"),
                    ("watchlist_standard", "Watchlist"),
                    ("watchlist_peps_only", "Watchlist (PEPs only)"),
                    ("watchlist_sanctions_only", "Watchlist (sanctions only)"),
                    ("proof_of_address", "Proof of Address"),
                    ("right_to_work", "Right to Work"),
                    ("check.photo_id", "Photo ID"),
                    (
                        "check.watchlist.peps_sanctions_media_extended",
                        "Watchlist (PEPs, Sanctions, Media, Extended)",
                    ),
                    ("check.dummy", "Dummy"),
                ],
                help_text="The name of the check - see https://developers.amiqus.co/aqid/api-reference.html#tag/Records/operation/get-checks-id",
                max_length=50,
            ),
        ),
    ]
