# Generated by Django 5.1.7 on 2025-04-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amiqus", "0003_alter_client_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="check_type",
            field=models.CharField(
                choices=[
                    ("check.credit", "Credit Report"),
                    ("check.criminal_record", "Criminal Record"),
                    ("check.identity", "Identity Report"),
                    ("check.photo_id", "Photo ID"),
                    ("check.employment_referencing", "Employment Referencing"),
                    ("check.reference", "Employment History"),
                    ("check.video", "Face Capture"),
                    ("check.watchlist", "Watchlist"),
                    ("check.dummy", "Dummy"),
                ],
                help_text="The name of the check - see https://developers.amiqus.co/aqid/api-reference.html#tag/Records/operation/get-checks-id",
                max_length=50,
            ),
        ),
    ]
